### ISSUE TITLE
TrustFailure

### ISSUE THREAD

**Issue by rudolfson** [peterhaneve/evemon#56] opened 2018-07-17 09:58 UTC
I get those pesky TrustFailures (e.g. instantly on startup while querying the server status). I can do a `curl -s -X GET "https://esi.evetech.net/latest/status/?datasource=tranquility" -H  "accept: application/json"` without any problems. Entering the url in Firefox / IE / Edge works, too.

The error message in EVEMon states there might be a problem with certificates. How are certificates in EVEMon validated? Does it come with its own trust store?

**Comment by peterhaneve** [comment] 2018-07-19 23:37
EVEMon does not have its own certificate store, and uses the Windows system certificates. If you are on Windows, most Cygwin and MinGW curl variants do have a separate store. Can the URL be accessed from IE or Edge?

**Comment by rudolfson** [comment] 2018-07-20 06:33
It works with IE and Edge.

I tried installing EVEMon and using the extracted Zip package - both give me a TrustFailure.

**Comment by rudolfson** [comment] 2018-07-20 07:46
So now I installed VS Community Edition, cloned this repo and started EVEMon from the project. Runs fine. :-)

Then I deleted `%USER_PROFILE%\AppData\Roaming\EVEMon` and `%USER_PROFILE%\AppData\Local\EVEMon_Development_Team` and started my local install of EVEMon. Works fine, too. :-)

**WARNING** Deleting those directories will delete all your skill plans, characters, etc..

**Comment by rudolfson** [comment] 2018-07-20 08:17
I closed this one too early.... sorry.

I can reproduce the TrustFailure. It seems to come from using "Cloud Storage Service". Now here is what I did to reproduce the error:
1. Go to "Options > Cloud Storage Service"
2. Press "Request Authentication" (you need a Dropbox account for that)
3. Enter the authentication code from Dropbox in the corresponding field in EVEMon
4. Check "Always download when EVEMon starts" above
5. Hit "Ok" and restart EVEMon
6. On restart you can cancel the download or save it somewhere, doesn't matter. All requests from then on give you the TrustFailure error.

So for the moment I will stick to not using the Dropbox.

**Comment by Tack122** [comment] 2018-07-27 14:05
Thanks rudolfson, your writeup resolved the issue for me, too bad about that cloud storage though, that seemed nice.

**Comment by peterhaneve** [comment] 2018-07-31 03:40
With these repro steps I was able to reproduce the issue. It turns out that in release builds only, using cloud service providers replaces the SSL certificate validation callback with a Dropbox version which rejects the CCP ESI certificates.

This issue should be fixed in bf7fa534.

**Closed by peterhaneve** 2018-07-31 03:40 UTC
