### ISSUE TITLE
501 - Header values specify a method that is not implemented.

### ISSUE THREAD

**Issue by poundjd** [peterhaneve/evemon#203] opened 2020-02-08 05:35 UTC
501 - Header values specify a method that is not implemented.
The page you are looking for cannot be displayed because a header value in the request does not match certain configuration settings on the Web server. For example, a request header might specify a POST to a static file that cannot be posted to, or specify a Transfer-Encoding value that cannot make use of compression.

**Comment by peterhaneve** [comment] 2020-02-11 08:25
Is this bug intended to be a duplicate of #204 ?

**Closed** 2020-02-26 21:06 UTC
