### ISSUE TITLE
Training time issue

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#268] opened 2021-01-09 10:20 UTC
The training time & SP/Hour on the new Salvage Drone Specialization skills are off:

![image](https://user-images.githubusercontent.com/1768983/104089126-7f436180-526c-11eb-88a0-2bb2bccaeefd.png)

The total queue time is ok though.

**Comment by peterhaneve** [comment] 2021-03-12 23:51
This issue is a duplicate of #270.

**Closed by peterhaneve** 2021-03-12 23:51 UTC
